### ISSUE TITLE
Konsumer rabbit-melding, parse rdf

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-rdf-parser-service#6]
Konsumerer meldinger fra reasoning-service.

Hent fdk-id fra changedCatalogs, id på alle kataloger parsing skal kjøres på.
Last ned turtle fra reasoning-service (uri fra katalogtype og id).
Kjør parse på hele katalog-data.

```
data class RabbitReport(
    val id: String,   # kan ignoreres
    val url: String,  # høsteurl
    val dataType: String,  # 
    val harvestError: Boolean
    val startTime: String,
    val endTime: String,
    val errorMessage: String? = null,
    val changedCatalogs: List[FdkIdAndUri] = emptyList(),
    val changedResources: List[FdkIdAndUri] = emptyList(),
    val removedResources: List[FdkIdAndUri] = emptyList()
)
```

Det er mange rapporter per melding, hver rapport er en høstekilde.

Filtrer vekk rapporter med `harvestError = true`

- Grupper per rapport
  - [POST per vellykkede rapport (json) til resource-service, til korrekt fdk-id.](https://github.com/Informasjonsforvaltning/fdk-rdf-parser-service/issues/50)
    - Samle 200-responser
  - Håndtere og samle feilmeldinger
  - Opprett vellykket eller feilet rapport avhengig av resultat fra operasjonene over (håndtering av rapport er vellykket om alt lykkes).
- Send melding til fulltext-search (+ ev. melding om feilede rapporter)

- sende rapport med liste over rapporter som har lykkes (akkumulert over kataloger) - parsing.datasets, parsing.concepts, osv.
- ev. sende rapport med liste over rapporter som feilet - parsing.failed

- En rabbit-melding inn, en melding ut (+ ev. feilmelding).
- startTime og endTime er for start og slutt på parse-jobb (menneskelesbart format)

### Annet
- fulltext-search trenger bare info om hvilken katalog-type den skal reindeksere (på key til rabbit?).
- harvest-admin trenger bare rapporter (rapportId)

## TODOs
- [x] #66
- [x] #64
- [x] #65

**Comment by KjerstiSteien** [comment]
@terjesyl er dette noe du jobber med nå?
